name: Continuous Integration with DOM/Javac
concurrency: 
    group: ${{ github.workflow }}-${{ github.ref }}-dom
    cancel-in-progress: true

on:
  push:
    branches: [ 'dom-based-operations', 'dom-with-javac' ]
  pull_request:
    branches: [ 'dom-based-operations', 'dom-with-javac' ]

jobs:
  build-dom-javac:
    runs-on: ubuntu-latest
    permissions:
      statuses: write
      checks: write
      contents: write
      pull-requests: write
      actions: write
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: recursive
        fetch-depth: 0
    - name: Enable DOM-first and Javac
      run: sed -i 's$</argLine>$ -DCompilationUnit.DOM_BASED_OPERATIONS=true -DSourceIndexer.DOM_BASED_INDEXER=false -DICompilationUnitResolver=org.eclipse.jdt.core.dom.JavacCompilationUnitResolver -DAbstractImageBuilder.compiler=org.eclipse.jdt.internal.javac.JavacCompiler_</argLine>$g' */pom.xml
    - name: Set up JDKs ☕
      uses: actions/setup-java@v3
      with:
        java-version: |
          8
          17
          20
        mvn-toolchain-id: |
          JavaSE-1.8
          JavaSE-17
          JavaSE-20
        distribution: 'temurin'
    - name: Set up Maven
      uses: stCarolas/setup-maven@07fbbe97d97ef44336b7382563d66743297e442f # v4.5
      with:
        maven-version: 3.9.3
    - name: Build with Maven 🏗️
      run: |
        mvn clean install --batch-mode -f org.eclipse.jdt.core.compiler.batch -DlocalEcjVersion=99.99
        mvn -U clean verify --batch-mode --fail-at-end -Ptest-on-javase-20 -Pbree-libs -Papi-check -Djava.io.tmpdir=$WORKSPACE/tmp -Dproject.build.sourceEncoding=UTF-8 -Dtycho.surefire.argLine="--add-modules ALL-SYSTEM -Dcompliance=1.8,11,17,20 -Djdt.performance.asserts=disabled" -Dcbi-ecj-version=99.99
    - name: Test Report
      uses: dorny/test-reporter@v1
      if: success() || failure()    # run this step even if previous step failed
      with:
        name: Surefire            # Name of the check run which will be created
        path: '*/target/surefire-reports/TEST-*.xml'    # Path to test results
        reporter: java-junit        # Format of test results
